# Generated by Django 3.0.3 on 2020-06-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='images/area')),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.AlterField(
            model_name='destination',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Area'),
        ),
    ]
