# Generated by Django 3.0.3 on 2020-07-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location_from',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location_to',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_name',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
