# Generated by Django 3.0.3 on 2020-06-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20200613_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='area_name',
        ),
    ]
