# Generated by Django 2.0 on 2020-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20200529_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_booking',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'done')], default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status_evaluete',
            field=models.IntegerField(choices=[(0, 'do_not'), (1, 'done')], default=0),
        ),
    ]
