# Generated by Django 3.0.3 on 2020-06-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20200613_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_photo', to='tour.Tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tour.Destination'),
        ),
    ]
