# Generated by Django 3.0.3 on 2020-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20200705_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location_from',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location_to',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
