# Generated by Django 2.0 on 2020-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20200529_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('teaser', models.TextField(blank=True, verbose_name='teaser')),
            ],
        ),
    ]
