# Generated by Django 2.0 on 2020-06-01 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_booking',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tour.Destination'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status_evaluete',
            field=models.IntegerField(choices=[(0, 'Do not'), (1, 'Done')], default=0),
        ),
    ]
