# Generated by Django 3.0.3 on 2020-06-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20200614_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='tour.Area'),
        ),
    ]
