# Generated by Django 3.0.3 on 2020-06-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20200614_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='tour.Area'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='des', to='tour.Destination'),
        ),
    ]
