# Generated by Django 2.0 on 2020-06-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20200601_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
