# Generated by Django 2.0 on 2020-06-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_auto_20200606_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
