# Generated by Django 2.0 on 2020-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
