# Generated by Django 2.0 on 2020-06-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
