# Generated by Django 2.0 on 2020-06-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0030_auto_20200608_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
