# Generated by Django 2.0 on 2020-06-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0031_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Tour'),
        ),
    ]
