# Generated by Django 2.0 on 2020-06-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0034_auto_20200609_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tour',
            new_name='tour_booking',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='tour',
            new_name='tour_photo',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='tour',
            new_name='tour_review',
        ),
    ]
