# Generated by Django 3.0.3 on 2020-06-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0039_auto_20200612_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
    ]
