# Generated by Django 3.0.3 on 2020-06-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0045_auto_20200612_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
